services:
  localdb:
    image: postgres:16.1
    ports:
      - '5432:5432'
    volumes:
      - ./db/dumps:/app-db-dumps
    environment:
      - POSTGRES_USER=local_user
      - POSTGRES_PASSWORD=taqlocal
      - POSTGRES_DB=local_db

  testdb:
    image: postgres:16.1
    ports:
      - '5433:5432'
    volumes:
      - ./db/dumps:/app-db-dumps
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=taqtest
      - POSTGRES_DB=test_db
